resources:
  - name: docker_push_webhook_res
    type: IncomingWebhook
    configuration:
      webhookName: docker_push_iw
  - name: integration_test_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory

pipelines:
  - name: integration_test
    steps:
    - name: test_env_deploy
      type: Bash
      configuration:
        inputResources:
          - name: docker_push_webhook_res
          - name: runpoppropin
      execution:
        onExecute:
          - echo "deploy"
    - name: smoketest
      type: Bash
      configuration:
        inputSteps:
          - name: test_env_deploy
      execution:
        onExecute:
          - echo "smoke_test"
    - name: integration_test
      type: Bash
      configuration:
        inputSteps:
          - name: test_env_deploy
        outputResources:
          - name: integration_test_info
      execution:
        onExecute:
          - echo "smoke_test"
    - name: promote_artifact
      type: Bash
      configuration:
        inputResources:
          - name: integration_test_info
      execution:
        onExecute:
          - echo "promote artifacts"